### PR TITLE
Make router.py listen on all interfaces

### PR DESCRIPTION
**Pull request by peterhaijen**
So we can have router.py running on dev system while working on enftun running on target

### CODE REVIEW

**Comment by peterhaijen** [comment]
O, I was under the impression that router.py was solely a development tool, and as such, would only ever be used by a developer in a safe environment anyway.

**Comment by peterhaijen** [comment]
Hi David, I added --bind and --port to specify IP/port.
I did a forced push, replacing my previous commit with a new one.
The new commit shows up automatically I see.

**Comment by drbild** [comment]
Thanks.

To be more Pythonic and allow router.py to be imported as a module, the args processing should go in an `if __name__ == "__main__":` block at the bottom of the script.

I'll change that when merging, unless you beat me to it.

**Comment by peterhaijen** [comment]
As I said, I'm not a python expert at all, so your input is appreciated.
I moved the argument processing to the bottom of the script.
I did not want to duplicate the default IP and port to bind to, so I made these parameters mandatory (I think) for the __init__ constructor (that's what it looks like and what I would call this in C++ land).

**Comment by drbild** [comment]
Thanks, LGTM!

**Pull request merged**
