### PR TITLE
Added info about installing dpkt module for python3

### PR DESCRIPTION
**Pull request by peterhaijen**
Hi @drbild lost some time this morning trying to figury out why router.py was not working as expected, and decided to document what I had to do to get router.py working on my system.

Also a good opportunity to do a test sending a pull request to you.

Regards

Peter

### CODE REVIEW

**Comment by peterhaijen** [comment]
Hi David

I'm not a python expert at all - when I chose my favorite scripting language python wasn't even on the menu. I had to do some fair amount of Googling around, and it is my impression that `pip install -r requirements.txt` may not have worked because:

- `pip` would probably default to whatever version of python is started when I run `python`, which is 2.x
- `apt-get install python-dpkt` actually installs dpkt, but for python 2, which is not compatible with `router.py`
- the recommendation is not to mix apt-get and pip together anyway, in order not to mess up your standard packaging system

The recommendation was to use a virtual environment if there is a need to install some module that is not available through the installed distribution, and this method works flawlessly for me. I added this to the README because this would have saved me some time, and may save others some time as well.

**Comment by peterhaijen** [comment]
Hi David

For python newbies like me, just writing `pip install -r requirements.txt` would not have been sufficient to get me going without Googling. So I added your preferred install method, noted that this preferred install method would probably have to be `pip3 install -r requirements.txt` on Debian-based systems (I did not test this) and added that for those who prefer not to touch the globally installed Python 3 environment, there is the possibility of using a virtual environment.

**Comment by drbild** [comment]
Makes sense, thanks. It's always a balance between providing enough to get started, but not becoming a copy of the user manual.

You're right - the default should be `pip3 install -r requirements.txt`.  `pip3` will always be available under that name - `pip` might be `pip2`.

I'll change that when I merged, if you don't beat me to it.

**Comment by drbild** [comment]
Merged in e7dc8db.

**Pull request closed without merging**
